site_name: Lichtara OS - Declaração de Propósito
site_description: Documentação da declaração de propósito do projeto Lichtara OS
site_author: Debora Lutz

# Configuração do tema
theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

# Estrutura de navegação
nav:
  - Início: index.md
  - Visão Geral: visao-geral.md
  - Missão e Valores: missao-valores.md
  - Objetivos: objetivos.md
  - Roadmap: roadmap.md
  - Contribuição: contribuicao.md

# Plugins
plugins:
  - search:
      lang: pt
  - git-revision-date-localized:
      type: date

# Configurações do Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Informações extras
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deboralutz/lichtara-os
  generator: false

# Configuração do repositório
repo_url: https://github.com/deboralutz/lichtara-os
repo_name: lichtara-os
edit_uri: edit/main/declaracao-de-proposito/docs/

# Diretório de documentos
docs_dir: docs
site_dir: site
